
import type { Crop } from '@/types';
import { Carrot, Wheat } from 'lucide-react'; // Lucide icons can still be fallbacks or primary if specific images are not set

export const CROPS_DATA: Crop[] = [
  {
    id: 'carrot',
    name: 'Carrot',
    growTime: 5 * 1000, // 5 seconds
    sellPrice: 5,
    seedPrice: 1,
    icon: Carrot, // Keep Lucide icon as potential display
    seedShopImageUrl: 'https://picsum.photos/seed/carrot-packet/64/64',
    dataAiHintSeedShop: 'carrot seedpacket',
    inventoryImageUrl: 'https://picsum.photos/seed/carrot-item/64/64',
    dataAiHintInventory: 'carrot vegetable',
    farmPlotImageUrl: 'https://picsum.photos/seed/carrot-plant/64/64',
    dataAiHintFarmPlot: 'carrot plant',
  },
  {
    id: 'radish',
    name: 'Radish',
    growTime: 6 * 1000,
    sellPrice: 7,
    seedPrice: 1,
    seedShopImageUrl: 'https://picsum.photos/seed/radish-packet/64/64',
    dataAiHintSeedShop: 'radish seedpacket',
    inventoryImageUrl: 'https://picsum.photos/seed/radish-item/64/64',
    dataAiHintInventory: 'radish vegetable',
    farmPlotImageUrl: 'https://picsum.photos/seed/radish-plant/64/64',
    dataAiHintFarmPlot: 'radish plant',
  },
  {
    id: 'wheat',
    name: 'Wheat',
    growTime: 10 * 1000, // 10 seconds
    sellPrice: 10,
    seedPrice: 2,
    icon: Wheat, // Keep Lucide icon
    seedShopImageUrl: 'https://picsum.photos/seed/wheat-sheaf/64/64',
    dataAiHintSeedShop: 'wheat seedbag',
    inventoryImageUrl: 'https://picsum.photos/seed/wheat-grain/64/64',
    dataAiHintInventory: 'wheat grain',
    farmPlotImageUrl: 'https://picsum.photos/seed/wheat-field/64/64',
    dataAiHintFarmPlot: 'wheat stalk',
  },
  {
    id: 'potato',
    name: 'Potato',
    growTime: 8 * 1000, // 8 seconds
    sellPrice: 8,
    seedPrice: 2,
    seedShopImageUrl: 'https://picsum.photos/seed/potato-sack/64/64',
    dataAiHintSeedShop: 'potato seedbag',
    inventoryImageUrl: 'https://picsum.photos/seed/potato-item/64/64',
    dataAiHintInventory: 'potato vegetable',
    farmPlotImageUrl: 'https://picsum.photos/seed/potato-sprout/64/64', 
    dataAiHintFarmPlot: 'potato plant',
  },
  {
    id: 'onion',
    name: 'Onion',
    growTime: 10 * 1000,
    sellPrice: 9,
    seedPrice: 2,
    seedShopImageUrl: 'https://picsum.photos/seed/onion-set/64/64',
    dataAiHintSeedShop: 'onion sets',
    inventoryImageUrl: 'https://picsum.photos/seed/onion-bulb/64/64',
    dataAiHintInventory: 'onion bulb',
    farmPlotImageUrl: 'https://picsum.photos/seed/onion-green/64/64',
    dataAiHintFarmPlot: 'onion plant',
  },
  {
    id: 'tomato',
    name: 'Tomato',
    growTime: 15 * 1000, // 15 seconds
    sellPrice: 15,
    seedPrice: 3,
    seedShopImageUrl: 'https://picsum.photos/seed/tomato-seedling/64/64',
    dataAiHintSeedShop: 'tomato seedpacket',
    inventoryImageUrl: 'https://picsum.photos/seed/tomato-fruit/64/64', 
    dataAiHintInventory: 'tomato fruit',
    farmPlotImageUrl: 'https://picsum.photos/seed/tomato-vine/64/64',
    dataAiHintFarmPlot: 'tomato plant',
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    growTime: 16 * 1000,
    sellPrice: 18,
    seedPrice: 3,
    seedShopImageUrl: 'https://picsum.photos/seed/broccoli-seeds/64/64',
    dataAiHintSeedShop: 'broccoli seeds',
    inventoryImageUrl: 'https://picsum.photos/seed/broccoli-floret/64/64',
    dataAiHintInventory: 'broccoli floret',
    farmPlotImageUrl: 'https://picsum.photos/seed/broccoli-head/64/64',
    dataAiHintFarmPlot: 'broccoli plant',
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    growTime: 14 * 1000,
    sellPrice: 16,
    seedPrice: 3,
    seedShopImageUrl: 'https://picsum.photos/seed/cucumber-pack/64/64',
    dataAiHintSeedShop: 'cucumber seedpacket',
    inventoryImageUrl: 'https://picsum.photos/seed/cucumber-slice/64/64',
    dataAiHintInventory: 'cucumber fruit',
    farmPlotImageUrl: 'https://picsum.photos/seed/cucumber-vine/64/64',
    dataAiHintFarmPlot: 'cucumber plant',
  },
  {
    id: 'garlic',
    name: 'Garlic',
    growTime: 12 * 1000,
    sellPrice: 11,
    seedPrice: 3,
    seedShopImageUrl: 'https://picsum.photos/seed/garlic-seed/64/64',
    dataAiHintSeedShop: 'garlic seedclove',
    inventoryImageUrl: 'https://picsum.photos/seed/garlic-clove/64/64',
    dataAiHintInventory: 'garlic bulb',
    farmPlotImageUrl: 'https://picsum.photos/seed/garlic-scape/64/64',
    dataAiHintFarmPlot: 'garlic plant',
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    growTime: 12 * 1000, // 12 seconds
    sellPrice: 12,
    seedPrice: 4,
    seedShopImageUrl: 'https://picsum.photos/seed/strawberry-runner/64/64',
    dataAiHintSeedShop: 'strawberry seedpacket',
    inventoryImageUrl: 'https://picsum.photos/seed/strawberry-fruit/64/64',
    dataAiHintInventory: 'strawberry fruit',
    farmPlotImageUrl: 'https://picsum.photos/seed/strawberry-bush/64/64',
    dataAiHintFarmPlot: 'strawberry plant',
  },
  {
    id: 'bellPepper',
    name: 'Bell Pepper',
    growTime: 18 * 1000,
    sellPrice: 20,
    seedPrice: 4,
    seedShopImageUrl: 'https://picsum.photos/seed/pepper-seeds/64/64',
    dataAiHintSeedShop: 'pepper seedpacket',
    inventoryImageUrl: 'https://picsum.photos/seed/bellpepper-item/64/64',
    dataAiHintInventory: 'bell pepper',
    farmPlotImageUrl: 'https://picsum.photos/seed/pepper-plant/64/64',
    dataAiHintFarmPlot: 'pepper plant',
  },
  {
    id: 'corn',
    name: 'Corn',
    growTime: 20 * 1000, 
    sellPrice: 25,
    seedPrice: 5,
    seedShopImageUrl: 'https://picsum.photos/seed/corn-kernel/64/64',
    dataAiHintSeedShop: 'corn seedpacket',
    inventoryImageUrl: 'https://picsum.photos/seed/corn-cob/64/64',
    dataAiHintInventory: 'corn cob',
    farmPlotImageUrl: 'https://picsum.photos/seed/corn-stalk/64/64',
    dataAiHintFarmPlot: 'corn stalk',
  },
  {
    id: 'cabbage',
    name: 'Cabbage',
    growTime: 22 * 1000,
    sellPrice: 28,
    seedPrice: 6,
    seedShopImageUrl: 'https://picsum.photos/seed/cabbage-starter/64/64',
    dataAiHintSeedShop: 'cabbage seedpacket',
    inventoryImageUrl: 'https://picsum.photos/seed/cabbage-head/64/64',
    dataAiHintInventory: 'cabbage head',
    farmPlotImageUrl: 'https://picsum.photos/seed/cabbage-leaf/64/64',
    dataAiHintFarmPlot: 'cabbage plant',
  },
  {
    id: 'eggplant',
    name: 'Eggplant',
    growTime: 25 * 1000,
    sellPrice: 30,
    seedPrice: 7,
    seedShopImageUrl: 'https://picsum.photos/seed/eggplant-small/64/64',
    dataAiHintSeedShop: 'eggplant seedpacket',
    inventoryImageUrl: 'https://picsum.photos/seed/eggplant-veg/64/64',
    dataAiHintInventory: 'eggplant vegetable',
    farmPlotImageUrl: 'https://picsum.photos/seed/eggplant-bush/64/64',
    dataAiHintFarmPlot: 'eggplant plant',
  },
  {
    id: 'pumpkin',
    name: 'Pumpkin',
    growTime: 30 * 1000,
    sellPrice: 40,
    seedPrice: 8,
    seedShopImageUrl: 'https://picsum.photos/seed/pumpkin-seedling/64/64',
    dataAiHintSeedShop: 'pumpkin seedpacket',
    inventoryImageUrl: 'https://picsum.photos/seed/pumpkin-fruit/64/64',
    dataAiHintInventory: 'pumpkin fruit',
    farmPlotImageUrl: 'https://picsum.photos/seed/pumpkin-vine/64/64',
    dataAiHintFarmPlot: 'pumpkin plant',
  },
].sort((a, b) => a.seedPrice - b.seedPrice);

