import type { Crop } from '@/types';
import { Carrot, Wheat, Sprout } from 'lucide-react'; // Sprout as a generic plant icon

export const CROPS_DATA: Crop[] = [
  {
    id: 'carrot',
    name: 'Carrot',
    growTime: 5 * 1000, // 5 seconds
    sellPrice: 5,
    seedPrice: 1,
    icon: Carrot,
  },
  {
    id: 'wheat',
    name: 'Wheat',
    growTime: 10 * 1000, // 10 seconds
    sellPrice: 10,
    seedPrice: 2,
    icon: Wheat,
  },
  {
    id: 'tomato',
    name: 'Tomato',
    growTime: 15 * 1000, // 15 seconds
    sellPrice: 15,
    seedPrice: 3,
    imageUrl: 'https://picsum.photos/id/1080/64/64', 
    dataAiHint: 'tomato plant',
  },
  {
    id: 'potato',
    name: 'Potato',
    growTime: 8 * 1000, // 8 seconds
    sellPrice: 8,
    seedPrice: 2,
    imageUrl: 'https://picsum.photos/id/1060/64/64', 
    dataAiHint: 'potato plant',
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    growTime: 12 * 1000, // 12 seconds
    sellPrice: 12,
    seedPrice: 4,
    // icon: Sprout, // Using Sprout as a placeholder, specific icon recommended
    imageUrl: 'https://picsum.photos/seed/strawberry/64/64',
    dataAiHint: 'strawberry plant',
  },
  {
    id: 'corn',
    name: 'Corn',
    growTime: 20 * 1000, 
    sellPrice: 25,
    seedPrice: 5,
    imageUrl: 'https://picsum.photos/seed/corncob/64/64',
    dataAiHint: 'corn cob',
  },
  {
    id: 'bellPepper',
    name: 'Bell Pepper',
    growTime: 18 * 1000,
    sellPrice: 20,
    seedPrice: 4,
    imageUrl: 'https://picsum.photos/seed/bellpepper/64/64',
    dataAiHint: 'bell pepper',
  },
  {
    id: 'cabbage',
    name: 'Cabbage',
    growTime: 22 * 1000,
    sellPrice: 28,
    seedPrice: 6,
    imageUrl: 'https://picsum.photos/seed/cabbagehead/64/64',
    dataAiHint: 'cabbage head',
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    growTime: 16 * 1000,
    sellPrice: 18,
    seedPrice: 3,
    imageUrl: 'https://picsum.photos/seed/broccolifloret/64/64',
    dataAiHint: 'broccoli floret',
  },
  {
    id: 'pumpkin',
    name: 'Pumpkin',
    growTime: 30 * 1000,
    sellPrice: 40,
    seedPrice: 8,
    imageUrl: 'https://picsum.photos/seed/pumpkinfruit/64/64',
    dataAiHint: 'pumpkin fruit',
  },
  {
    id: 'eggplant',
    name: 'Eggplant',
    growTime: 25 * 1000,
    sellPrice: 30,
    seedPrice: 7,
    imageUrl: 'https://picsum.photos/seed/eggplantveg/64/64',
    dataAiHint: 'eggplant vegetable',
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    growTime: 14 * 1000,
    sellPrice: 16,
    seedPrice: 3,
    imageUrl: 'https://picsum.photos/seed/cucumberslice/64/64',
    dataAiHint: 'cucumber slice',
  },
  {
    id: 'radish',
    name: 'Radish',
    growTime: 6 * 1000,
    sellPrice: 7,
    seedPrice: 1,
    imageUrl: 'https://picsum.photos/seed/radishroot/64/64',
    dataAiHint: 'radish root',
  },
  {
    id: 'onion',
    name: 'Onion',
    growTime: 10 * 1000,
    sellPrice: 9,
    seedPrice: 2,
    imageUrl: 'https://picsum.photos/seed/onionbulb/64/64',
    dataAiHint: 'onion bulb',
  },
  {
    id: 'garlic',
    name: 'Garlic',
    growTime: 12 * 1000,
    sellPrice: 11,
    seedPrice: 3,
    imageUrl: 'https://picsum.photos/seed/garlicclove/64/64',
    dataAiHint: 'garlic clove',
  },
];
